services:
  app:
    image: ecommerce:dev
    container_name: ecommerce-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ecommerce-backend
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Ecommerce
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    networks:
      - ecommerce-backend
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
    name: mysql-data

networks:
  ecommerce-backend:
    name: ecommerce-backend
