# Use nodejs 18 alpine as base image
FROM node:18-alpine

# Set the working directory
WORKDIR /home/node/app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Copy prisma
COPY prisma ./prisma/

# Install dependencies using yarn
RUN yarn install

# Copy the rest of the files
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["yarn", "start:dev"]
