name: Ecommerce App Deployment
run-name: ${{ github.actor }} is deploying app
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu:22.04
    # runs-on: ubuntu-latest
    steps:
      - name: List files in the repository 1
        run: |
          ls ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - name: List files in the repository 2
        run: |
          ls ${{ github.workspace }}
      - run: echo "job's status ${{ job.status }}."
