name: Ecommerce App Deployment
run-name: ${{ github.actor }} deploying app
on: [push]
jobs:
  Deployment:
    if: ${{ 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Github context
        run: ${{ toJson(github) }}

      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      # - run: yarn test
